project:
  type: website

website:
<<<<<<< HEAD
  title: "Mixnotes"
=======
  title: "xminotes"
>>>>>>> 3d225eab81b78853c3a269f0ca81f4c8698598a8
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

<<<<<<< HEAD

=======
editor: visual
>>>>>>> 3d225eab81b78853c3a269f0ca81f4c8698598a8

